recipe: default.v1
language: en
assistant_id: level2-agent

pipeline:
  - name: SearchReadyLLMCommandGenerator
    llm:
      model_group: rasa_command_generation_model
    flow_retrieval:
      active: false

policies:
  - name: FlowPolicy
