- assignment: c624c6207564c7ee228de3010b0e3a5b
  section: ["Level 3 - Slot Collection", "Unit 0: Recap - What you built in Level 2"]
  paths: &l3
    - "level3/**"
    - "level4/**"
    - ".guides/styles.css"
    - ".guides/img/**"
    - ".codio"
    - ".gitignore"

- assignment: c624c6207564c7ee228de3010b0e3a5b
  section: ["Level 3 - Slot Collection", "Unit 1: Introduction to Memory"]
  paths: *l3

- assignment: c624c6207564c7ee228de3010b0e3a5b
  section: ["Level 3 - Slot Collection", "Unit 2: Defining Slots in the Domain"]
  paths: *l3

- assignment: c624c6207564c7ee228de3010b0e3a5b
  section: ["Level 3 - Slot Collection", "Unit 3: Reading Slots in Actions"]
  paths: *l3

- assignment: c624c6207564c7ee228de3010b0e3a5b
  section: ["Level 3 - Slot Collection", "Unit 4: Collecting Slots in Flows"]
  paths: *l3

- assignment: c624c6207564c7ee228de3010b0e3a5b
  section: ["Level 3 - Slot Collection", "Unit 5: Training and Testing with Slots"]
  paths: *l3

- assignment: c624c6207564c7ee228de3010b0e3a5b
  section: ["Level 3 - Slot Collection", "Unit 6: Assessment and Next Steps"]
  paths: *l3
